<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE patient [
	<!ELEMENT patient (dob,address,phoneNumber,eMail,sport,disability,medicalHistory,appointments?)>
	<!ATTLIST patient name CDATA #REQUIRED>
	<!ELEMENT dob (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
	<!ELEMENT phoneNumber (#PCDATA)>
	<!ELEMENT eMail (#PCDATA)>
	<!ELEMENT sport (#PCDATA)>
	<!ELEMENT disability (#PCDATA)>
	<!ELEMENT medicalHistory (Diseases,Allergies,Surgeries,WeightKg,HeightCm)>
	<!ATTLIST medicalHistory id CDATA #REQUIRED>
	<!ELEMENT Diseases (#PCDATA) >
	<!ELEMENT Allergies (#PCDATA) >
	<!ELEMENT Surgeries (#PCDATA) >
	<!ELEMENT WeightKg (#PCDATA) >
	<!ELEMENT HeightCm (#PCDATA) >
	<!ELEMENT appointments (appointment*)>
	<!ELEMENT appointment (date,time,doc,pt)>
	<!ELEMENT date (#PCDATA) >
	<!ELEMENT time (#PCDATA) >
	<!ELEMENT doc (id,eMail,specialty)>
	<!ELEMENT id (#PCDATA)>
	<!ATTLIST doc name CDATA #REQUIRED>
	<!ELEMENT specialty (#PCDATA) >
	<!ELEMENT pt (id,eMail,typeSport)>
	<!ATTLIST pt name CDATA #REQUIRED>
	<!ELEMENT typeSport (#PCDATA)>	
]>

<patient name="Daniel Caverzaschi">
    <dob>1993-07-11</dob>
    <address>Alcobendas</address>
    <phoneNumber>678374628</phoneNumber>
    <eMail>danielcaverzaschi@gmail.com</eMail>
    <sport>Tennis</sport>
    <disability>Missing femur and knee on the right leg</disability>
    <medicalHistory id="3">
        <Diseases>muscular distension</Diseases>
        <Allergies>none</Allergies>
        <Surgeries>Several surgeries in the left leg</Surgeries>
        <WeightKg>80.3</WeightKg>
        <HeightCm>182</HeightCm>
    </medicalHistory>
    <appointments>
        <appointment>
            <date>2020-07-21</date>
            <time>14:00:00</time>
            <doc name="Cristina Ubeda">
                <id>1</id>
                <eMail>cris@gmail.com</eMail>
                <specialty>Orthopedics</specialty>
            </doc>
            <pt name="Juan Carlos Serraon">
                <id>1</id>
                <eMail>jcarlos@gmail.com</eMail>
                <typeSport>Tennis</typeSport>
            </pt>
        </appointment>
        <appointment>
            <date>2020-09-09</date>
            <time>13:30:00</time>
            <doc name="Cristina Ubeda">
                <id>1</id>
                <eMail>cris@gmail.com</eMail>
                <specialty>Orthopedics</specialty>
            </doc>
            <pt name="Juan Carlos Serraon">
                <id>1</id>
                <eMail>jcarlos@gmail.com</eMail>
                <typeSport>Tennis</typeSport>
            </pt>
        </appointment>
    </appointments>
</patient>